### ISSUE TITLE
Woo Product Meta Widget Doesn't Respect Language Translation

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#5685]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When using Product Meta Widget on Product template it uses English meta description, even though translation exists and is used by theme's native Product page. See the screenshot below:

![obrazek](https://user-images.githubusercontent.com/5634870/45152109-61631f00-b1d0-11e8-985e-9b07a1e94310.png)

An alternative way could be an option to use custom texts for description. 

In addition, it would be also nice to have an option to remove some of the metas. But this is more of a feature request (maybe even the translation is, but I consider it a bug).

## Steps to reproduce
Use Product Meta Widget on a non-English site (in my case Czech).

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 10.0.36
	PHP Version: 7.0.31
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://www.bioapoteka.cz/apoteka-nova
	Home URL: https://www.bioapoteka.cz/apoteka-nova
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: cs-CZ
	Timezone: Europe/Prague
	Debug Mode: Inactive

== Theme ==
	Name: Remedical WPBF
	Version: 1.0.0
	Author: Petr Jandák
	Child Theme: Yes
	Parent Theme Name: Page Builder Framework
	Parent Theme Version: 1.9
	Parent Theme Author: David Vongries

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

== Active Plugins ==
	Admin Menu Editor
		Version: 1.8.4
		Author: Janis Elsts

	Advanced Custom Fields PRO
		Version: 5.7.4
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 6.75
		Author: ServMask

	Central Color Palette
		Version: 1.12.5
		Author: Gáravo

	Clean Image Filenames
		Version: 1.2.1
		Author: Upperdog

	Customizer Export/Import
		Version: 0.8
		Author: The Beaver Builder Team

	Disable Comments
		Version: 1.7.1
		Author: Samir Shah

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.2.1
		Author: Elementor.com

	Elementor Extras
		Version: 1.9.14
		Author: Namogo

	Elementor Pro
		Version: 2.1.7
		Author: Elementor.com

	Intuitive Custom Post Order
		Version: 3.1.1
		Author: hijiri

	iThemes Security
		Version: 7.1.0
		Author: iThemes

	Nested Pages
		Version: 3.0.6
		Author: Kyle Phillips

	Page Builder Framework Premium Addon
		Version: 1.9
		Author: MapSteps

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	TinyMCE Advanced
		Version: 4.8.0
		Author: Andrew Ozz

	Ultimate Addons for Elementor
		Version: 1.7.0
		Author: Brainstorm Force

	User Profile Picture
		Version: 1.5.5
		Author: Ronald Huereca

	Woo Checkout Field Editor Pro
		Version: 1.2.8
		Author: ThemeHiGH

	WooCommerce
		Version: 3.4.5
		Author: Automattic

	Woo Doprava
		Version: 1.5.6
		Author: Vladislav Musílek

	Woo GoPay Inline
		Version: 1.5.8
		Author: Vladislav Musílek

	WP All Import
		Version: 3.4.9
		Author: Soflyy

	WP Media folder
		Version: 4.7.0
		Author: Joomunited

	Zalomení
		Version: 1.4.7
		Author: Honza Skypala


== Debug ==
	Errors: 
		TypeError: this._parent is undefined
			at https://www.bioapoteka.cz/apoteka-nova/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.0 - 2:192295
			2018-08-30 14:57 +00:00
			x 8 times

		TypeError: this._parent is undefined
			at https://www.bioapoteka.cz/apoteka-nova/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:139138
			2018-08-12 22:30 +00:00
```
</details>

**Comment by bainternet** [comment]
@black-eye 

All of these (SKU, Categories and Tags) are wrapped in translations functions, which means that they have not yet been translated in Elementor Pro for the Czech language.

But they are translatable.


thanks for reporting.

**Comment by black-eye** [comment]
OK, but why aren't you using the native WooCommerce terms at first place? (Or is it impossible?)
Considering really terrible Czech translation of Elementor, I'm afraid of the results when (if) they come. 

(Sorry for being harsh here, but the poor Czech translation is a pure fact, it makes Elementor practically unusable - I have to turn the translation off on every install I have).

**Comment by JoeDarko** [comment]
To add to this. Czech translation is mostly translated by Google Translate. I have no idea how this can be approved. And i'm not saying it is translated so badly it looks like Google Translate, i'm, saying somebody is literally just copy-pasting the strings to Google Translate, it's very obvious.

So while you are painstakingly improving every little detail of Elementor, plenty of your users are getting Elementor that is a nightmare to use, because it's badly translated/machine translated or because translating web developement terms is confusing for a lot of people.
