### ISSUE TITLE
Tracking events with Google Analytics and Yandex Metrika help needed

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#6331]
- [x] I wrote to general support and they said that incompetent in this question and advice to write in Github

**What instructions I've seen**
- [x] I've got a code below from this example https://github.com/pojome/elementor/issues/838#issuecomment-401800712 and mixed it with form track tutorial from this page https://docs.elementor.com/article/281-form-faq
- [x] I know about this button tracking instruction https://docs.elementor.com/article/59-button

**Issue summary**
I'm trying to track 2 buttons and 2 forms apart with different IDs using Google Analytics (analytics.js) and Yandex Metrika on one landing page, using this code:
```
<script type="text/javascript">
jQuery( document ).ready(function( $ ){
//Buttons
	$( '#coach-button' ).on('click', function(){
		ga( 'send', 'event', 'button', 'click', 'Coaching' );
		yaCounter51353500.reachGoal('сoaching-button');
	});
	
	$( '#club-button' ).on('click', function(){
		ga( 'send', 'event', 'button', 'click', 'Club' );
		yaCounter51353500.reachGoal('club-button');
	});
	
//Forms
	$( '#coach-form' ).on('submit_success', function(){
		ga('send', 'event', 'Lead', 'Submit', 'Coaching');
		yaCounter51353500.reachGoal('сoaching-form');
	});
	
	$( '#club-form' ).on('submit_success', function(){
		ga('send', 'event', 'Lead', 'Submit', 'Club');
		yaCounter51353500.reachGoal('club-form');
	});
});
</script>
```
**How I insert this code**
 In footer after jQuery connection string and GA/YM tracking codes.

**What works and what is not**
#coach-button, #club-button and #coach-form tracks good in both services (GA and YM) but #club-form — not.

**How i tried to debug**
I checked tracking with Yandex Metrika debug procedure `http://example.com/?_ym_debug=1` and then looked for event in browser developer tools console.
For the three first codes (#coach-button, #club-button and #coach-form) I see normal events processing but for the last (#club-form) — nothing at all.

What am I doing wrong?

**Comment by bainternet** [comment]
@parfilov 	

doesn't look like you are doing something wrong, the only issue I can think of is that your `#club-form` form ID is not set correctly but I can't tell without checking.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
